# Form implementation generated from reading ui file 'administer_login3.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from Database.testconnection import getDatabase


class Ui_adLogin3(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(230, 120, 301, 141))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 310, 301, 141))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 20, 261, 61))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "辅助注册新用户"))
        self.pushButton_2.setText(_translate("MainWindow", "查看并管理当前人员信息"))

    # 获取管理员姓名
    def getad_Name(self, ad_account):
        self.ad_account = ad_account
        self.ad_name = self.Findad_Name(ad_account)
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("MainWindow", "欢迎您，管理员" + self.ad_name + "："))

    # 寻找管理员姓名
    def Findad_Name(self, ad_account):
        db = getDatabase()
        cursor = db.cursor()
        sql = "select ad_Name from administrator where ad_account = " + ad_account + ""
        cursor.execute(sql)
        result = cursor.fetchall()
        # 修改
        db.commit()
        # 关闭游标
        cursor.close()
        return result[0][0]

    # 返回管理员账号
    def getADaccount(self):
        return self.ad_account

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_adLogin3()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
